create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug = lower(slug)),
  name text not null check (char_length(name) between 2 and 120),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.workspace_invites (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null check (email = lower(email) and char_length(email) between 3 and 320),
  full_name text,
  role text not null default 'viewer' check (role in ('owner', 'admin', 'analyst', 'viewer')),
  accepted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists workspace_invites_workspace_email_key
  on public.workspace_invites (workspace_id, lower(email));

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null check (email = lower(email) and char_length(email) between 3 and 320),
  full_name text not null check (char_length(full_name) between 1 and 120),
  role text not null default 'viewer' check (role in ('owner', 'admin', 'analyst', 'viewer')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create unique index if not exists workspace_members_workspace_email_key
  on public.workspace_members (workspace_id, lower(email));

create table if not exists public.workspace_access_requests (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null check (email = lower(email) and char_length(email) between 3 and 320),
  full_name text,
  note text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  handled_at timestamptz,
  handled_by uuid references auth.users(id) on delete set null
);

create index if not exists workspace_access_requests_status_requested_at_idx
  on public.workspace_access_requests (workspace_id, status, requested_at desc);

create table if not exists public.workspace_login_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  provider text not null check (provider in ('email', 'google', 'unknown')),
  user_agent text,
  signed_in_at timestamptz not null default now()
);

create index if not exists workspace_login_events_user_time_idx
  on public.workspace_login_events (user_id, signed_in_at desc);

create or replace function public.set_workspace_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_workspaces_updated_at on public.workspaces;
create trigger set_workspaces_updated_at
before update on public.workspaces
for each row execute function public.set_workspace_updated_at();

drop trigger if exists set_workspace_invites_updated_at on public.workspace_invites;
create trigger set_workspace_invites_updated_at
before update on public.workspace_invites
for each row execute function public.set_workspace_updated_at();

drop trigger if exists set_workspace_members_updated_at on public.workspace_members;
create trigger set_workspace_members_updated_at
before update on public.workspace_members
for each row execute function public.set_workspace_updated_at();

create or replace function public.is_workspace_member(target_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = (select auth.uid())
      and status = 'active'
  );
$$;

create or replace function public.is_workspace_admin(target_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.workspace_members
    where workspace_id = target_workspace_id
      and user_id = (select auth.uid())
      and status = 'active'
      and role in ('owner', 'admin')
  );
$$;

revoke all on function public.is_workspace_member(uuid) from public;
revoke all on function public.is_workspace_admin(uuid) from public;
grant execute on function public.is_workspace_member(uuid) to authenticated;
grant execute on function public.is_workspace_admin(uuid) to authenticated;

alter table public.workspaces enable row level security;
alter table public.workspace_invites enable row level security;
alter table public.workspace_members enable row level security;
alter table public.workspace_access_requests enable row level security;
alter table public.workspace_login_events enable row level security;

drop policy if exists "members can read workspaces" on public.workspaces;
create policy "members can read workspaces"
on public.workspaces for select to authenticated
using (public.is_workspace_member(id));

drop policy if exists "members can read their membership" on public.workspace_members;
create policy "members can read their membership"
on public.workspace_members for select to authenticated
using (user_id = (select auth.uid()) or public.is_workspace_admin(workspace_id));

drop policy if exists "admins can manage workspace members" on public.workspace_members;
create policy "admins can manage workspace members"
on public.workspace_members for all to authenticated
using (public.is_workspace_admin(workspace_id))
with check (public.is_workspace_admin(workspace_id));

drop policy if exists "admins can manage invites" on public.workspace_invites;
create policy "admins can manage invites"
on public.workspace_invites for all to authenticated
using (public.is_workspace_admin(workspace_id))
with check (public.is_workspace_admin(workspace_id));

drop policy if exists "admins can review access requests" on public.workspace_access_requests;
create policy "admins can review access requests"
on public.workspace_access_requests for select to authenticated
using (public.is_workspace_admin(workspace_id));

drop policy if exists "admins can update access requests" on public.workspace_access_requests;
create policy "admins can update access requests"
on public.workspace_access_requests for update to authenticated
using (public.is_workspace_admin(workspace_id))
with check (public.is_workspace_admin(workspace_id));

drop policy if exists "members can record their login" on public.workspace_login_events;
create policy "members can record their login"
on public.workspace_login_events for insert to authenticated
with check (
  user_id = (select auth.uid())
  and public.is_workspace_member(workspace_id)
);

drop policy if exists "admins can review login events" on public.workspace_login_events;
create policy "admins can review login events"
on public.workspace_login_events for select to authenticated
using (public.is_workspace_admin(workspace_id));

revoke all on public.workspaces from anon, authenticated;
revoke all on public.workspace_invites from anon, authenticated;
revoke all on public.workspace_members from anon, authenticated;
revoke all on public.workspace_access_requests from anon, authenticated;
revoke all on public.workspace_login_events from anon, authenticated;

grant select on public.workspaces to authenticated;
grant select, insert, update, delete on public.workspace_invites to authenticated;
grant select, insert, update, delete on public.workspace_members to authenticated;
grant select, update on public.workspace_access_requests to authenticated;
grant select, insert on public.workspace_login_events to authenticated;
grant usage, select on sequence public.workspace_login_events_id_seq to authenticated;

create or replace function public.request_workspace_access(
  p_email text,
  p_full_name text default null,
  p_note text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_email text := lower(trim(p_email));
  target_workspace_id uuid;
  existing_request_id uuid;
  created_request_id uuid;
begin
  if normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
    or char_length(normalized_email) > 320 then
    raise exception 'A valid work email is required.' using errcode = '22023';
  end if;

  if p_full_name is not null and char_length(trim(p_full_name)) > 120 then
    raise exception 'Full name is too long.' using errcode = '22023';
  end if;

  if p_note is not null and char_length(trim(p_note)) > 1000 then
    raise exception 'Request note is too long.' using errcode = '22023';
  end if;

  select id into target_workspace_id
  from public.workspaces
  where slug = 'decision-workspace';

  if target_workspace_id is null then
    raise exception 'Workspace is not configured.';
  end if;

  select id into existing_request_id
  from public.workspace_access_requests
  where workspace_id = target_workspace_id
    and email = normalized_email
    and status = 'pending'
    and requested_at > now() - interval '24 hours'
  order by requested_at desc
  limit 1;

  if existing_request_id is not null then
    return existing_request_id;
  end if;

  insert into public.workspace_access_requests (workspace_id, email, full_name, note)
  values (
    target_workspace_id,
    normalized_email,
    nullif(trim(coalesce(p_full_name, '')), ''),
    nullif(trim(coalesce(p_note, '')), '')
  )
  returning id into created_request_id;

  return created_request_id;
end;
$$;

revoke all on function public.request_workspace_access(text, text, text) from public;
grant execute on function public.request_workspace_access(text, text, text) to anon, authenticated;

create or replace function public.record_workspace_login(
  p_provider text default 'unknown',
  p_user_agent text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := (select auth.uid());
  current_email text;
  current_workspace_id uuid;
  created_event_id bigint;
begin
  if current_user_id is null then
    raise exception 'Authentication is required.' using errcode = '42501';
  end if;

  select email into current_email from auth.users where id = current_user_id;
  select workspace_id into current_workspace_id
  from public.workspace_members
  where user_id = current_user_id and status = 'active'
  order by created_at
  limit 1;

  if current_workspace_id is null then
    raise exception 'Workspace access is not approved.' using errcode = '42501';
  end if;

  insert into public.workspace_login_events (workspace_id, user_id, email, provider, user_agent)
  values (
    current_workspace_id,
    current_user_id,
    lower(current_email),
    case when p_provider in ('email', 'google') then p_provider else 'unknown' end,
    left(nullif(trim(coalesce(p_user_agent, '')), ''), 500)
  )
  returning id into created_event_id;

  return created_event_id;
end;
$$;

revoke all on function public.record_workspace_login(text, text) from public;
grant execute on function public.record_workspace_login(text, text) to authenticated;

create or replace function public.handle_workspace_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  pending_invite public.workspace_invites%rowtype;
  resolved_name text;
begin
  if new.email is null then
    return new;
  end if;

  select * into pending_invite
  from public.workspace_invites
  where email = lower(new.email)
    and accepted_at is null
  order by created_at
  limit 1;

  if pending_invite.id is null then
    return new;
  end if;

  resolved_name := coalesce(
    nullif(trim(pending_invite.full_name), ''),
    nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
    split_part(new.email, '@', 1)
  );

  insert into public.workspace_members (workspace_id, user_id, email, full_name, role, status)
  values (pending_invite.workspace_id, new.id, lower(new.email), resolved_name, pending_invite.role, 'active')
  on conflict (workspace_id, user_id) do update
  set email = excluded.email,
      full_name = excluded.full_name,
      role = excluded.role,
      status = 'active',
      updated_at = now();

  update public.workspace_invites
  set accepted_at = coalesce(accepted_at, now())
  where id = pending_invite.id;

  return new;
end;
$$;

drop trigger if exists on_auth_user_workspace_invite on auth.users;
create trigger on_auth_user_workspace_invite
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_workspace_auth_user();

insert into public.workspaces (slug, name)
values ('decision-workspace', 'Decision Workspace')
on conflict (slug) do update set name = excluded.name;

insert into public.workspace_invites (workspace_id, email, full_name, role)
select id, 'tien@redagency.vn', 'Tien Duong', 'owner'
from public.workspaces
where slug = 'decision-workspace'
on conflict (workspace_id, (lower(email))) do update
set full_name = excluded.full_name,
    role = excluded.role,
    updated_at = now();
